steps:

  - records:
      equals: "indent 2"
      first_field: "indent 2"
      field_comment: 2
      deriving: 2

  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: none
      list_align: after_alias
      pad_module_names: true
      long_list_align: multiline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: false
      space_surround: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - tabs:
      spaces: 4

  - trailing_whitespace: {}

columns: 80
newline: native
cabal: true
